backend:
  name: github
  repo: mcpmarko83/milosavljevic-smart-energy
  branch: main
  base_url: https://decap-cms-oauth-provider-for-github.netlify.app

media_folder: "Nasi projekti/uploads"
public_folder: "/Nasi projekti/uploads"

collections:
  - name: "config"
    label: "Sadržaj sajta"
    files:
      - label: "Lista projekata"
        name: "projekti"
        file: "podaci/projekti.json"
        fields:
          - label: "Projekti"
            name: "lista"
            widget: "list"
            fields:
              - {label: "Naziv", name: "title", widget: "string"}
              - {label: "Opis", name: "opis", widget: "string"}
              - {label: "Boja", name: "boja", widget: "string", default: "#4caf50"}
              - {label: "Putanja", name: "folder_path", widget: "string"}
